# Site settings
title: coding vs. coding
header-img: img/home-bg.png
email: alicewtien@gmail.com
copyright_name: alicewtien
description: > # this means to ignore newlines until "baseurl:"
  1 and 2 and 3 and...
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  alicewtien
learn_profile: alicewtien
email_username: alicewtien@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
